---
deployment:
  tasks:
    - export DEPLOYPATH=/home/n1577873/public_html/
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R icons $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R plugins $DEPLOYPATH
    - /bin/cp -R umum $DEPLOYPATH